"use client";

import { useState } from "react";

type Surface = "register" | "enterprise" | "admin";
type Policy = { score:number; title:string; meta:string; amount:string; deadline:string; reason:string; status:string; region:string };

const policies: Policy[] = [
  { score:92,title:"2026年度科技型中小企业技术创新资金项目",meta:"北京市科学技术委员会 · 科技资金",amount:"最高 200 万元",deadline:"09月30日截止",reason:"行业领域、研发投入及企业规模均符合申报要求",status:"申报中",region:"北京市" },
  { score:86,title:"专精特新中小企业高质量发展专项支持",meta:"工业和信息化部 · 资质认定",amount:"最高 100 万元",deadline:"10月18日截止",reason:"符合中小企业规模要求，知识产权条件仍需补充",status:"申报中",region:"国家级" },
  { score:78,title:"企业研发费用加计扣除政策指引",meta:"国家税务总局 · 税收优惠",amount:"研发费用 100% 加计扣除",deadline:"长期有效",reason:"研发活动符合范围，需确认研发费用归集情况",status:"长期有效",region:"国家级" },
  { score:74,title:"北京市企业技术中心创建工作通知",meta:"北京市经济和信息化局 · 平台认定",amount:"认定后享配套支持",deadline:"09月02日截止",reason:"研发组织条件基本符合，营收规模待确认",status:"即将截止",region:"北京市" },
];
const enterpriseNav = [["概览","⌂"],["政策库","▤"],["AI 政策助手","✦"],["企业画像","◎"],["政策匹配","◇"],["我的关注","☆"]];
const adminNav = [["运营概览","⌂"],["数据源管理","⌁"],["采集任务","↻"],["政策审核","✓"],["政策管理","▤"],["企业与线索","◎"],["AI 问答记录","✦"]];

export default function PrototypeClient(){
  const [surface,setSurface]=useState<Surface>("enterprise");
  const [enterpriseView,setEnterpriseView]=useState("概览");
  const [adminView,setAdminView]=useState("运营概览");
  return <div className="prototype-frame">
    <div className="demo-switcher"><span><i/>一期原型演示</span><div><button className={surface==="register"?"selected":""} onClick={()=>setSurface("register")}>官网注册</button><button className={surface==="enterprise"?"selected":""} onClick={()=>setSurface("enterprise")}>企业端</button><button className={surface==="admin"?"selected":""} onClick={()=>setSurface("admin")}>运营端</button></div><small>点击切换演示角色</small></div>
    {surface==="register"&&<Register onComplete={()=>setSurface("enterprise")}/>} {surface==="enterprise"&&<EnterpriseApp view={enterpriseView} onView={setEnterpriseView}/>} {surface==="admin"&&<AdminApp view={adminView} onView={setAdminView}/>} 
  </div>
}

function Register({onComplete}:{onComplete:()=>void}){
  const [step,setStep]=useState(1);
  return <main className="register-page"><section className="register-story"><div className="brand light"><span className="brand-mark">企</span><span><b>企策通</b><small>科技政策服务平台</small></span></div><div className="register-message"><span className="eyebrow">让政策主动找到企业</span><h1>一次企业体检，<br/>看清能报什么、还缺什么</h1><p>基于权威政策原文与企业真实画像，为科技企业提供可解释的政策匹配和申报条件诊断。</p><div className="trust-row"><span>✓ 政策原文可追溯</span><span>✓ 企业数据安全保护</span><span>✓ 专业顾问人工复核</span></div></div><div className="story-proof"><b>2,386</b><span>条权威政策持续更新</span><i/><b>92%</b><span>示例企业最高匹配度</span></div></section><section className="register-form-wrap"><div className="register-form"><div className="step-line"><span className="done">1</span><i className={step===2?"done":""}/><span className={step===2?"done":""}>2</span></div><p className="step-labels"><span>创建账号</span><span>企业信息</span></p>{step===1?<><FormTitle n="01" title="创建企业账号" text="用于接收政策提醒和保存测评结果"/><label>手机号码<input defaultValue="138 0000 6688"/></label><label>短信验证码<div className="field-combo"><input defaultValue="623819"/><button>重新获取 42s</button></div></label><label className="check"><input type="checkbox" defaultChecked/>我已阅读并同意《用户服务协议》和《隐私政策》</label><button className="form-submit" onClick={()=>setStep(2)}>下一步：填写企业信息 <span>→</span></button></>:<><FormTitle n="02" title="完善企业基本信息" text="仅需基础信息，进入平台后可继续补充"/><label>企业名称<input defaultValue="北京星云科技有限公司"/></label><label>统一社会信用代码<input defaultValue="91110108MA01XXXXXX"/></label><div className="two-fields"><label>所属地区<select><option>北京市</option></select></label><label>所属行业<select><option>软件和信息技术服务业</option></select></label></div><button className="form-submit" onClick={onComplete}>完成注册并进入平台 <span>→</span></button><button className="form-back" onClick={()=>setStep(1)}>返回上一步</button></>}<p className="login-tip">已有账号？<b>立即登录</b></p></div></section></main>
}
function FormTitle({n,title,text}:{n:string;title:string;text:string}){return <div className="form-title"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>}

function SideBar({type,items,active,onView}:{type:"enterprise"|"admin";items:string[][];active:string;onView:(v:string)=>void}){return <aside className={`sidebar ${type==="admin"?"admin-side":""}`}><div className="brand"><span className="brand-mark">企</span><span><b>企策通</b><small>{type==="admin"?"政策运营管理中心":"科技政策服务平台"}</small></span></div><nav>{items.map(([label,icon])=><button onClick={()=>onView(label)} className={active===label?"nav-item active":"nav-item"} key={label}><span>{icon}</span>{label}{label==="政策审核"&&<em>12</em>}</button>)}</nav>{type==="enterprise"?<div className="sidebar-help"><span className="help-icon">?</span><b>需要申报帮助？</b><p>专业顾问为您解读政策</p><button>联系政策顾问</button></div>:<div className="system-status"><i/>政策采集服务正常<small>最后同步：16:28</small></div>}<div className="user-row"><span className="avatar">{type==="admin"?"周":"陈"}</span><span><b>{type==="admin"?"周运营":"陈先生"}</b><small>{type==="admin"?"政策运营专员":"北京星云科技"}</small></span><i>⌄</i></div></aside>}
function AppHeader({title,subtitle}:{title:string;subtitle:string}){return <header className="topbar"><div><p>{subtitle}</p><h1>{title}</h1></div><div className="top-actions"><button className="search">⌕ <span>搜索政策、企业或关键词</span><kbd>⌘ K</kbd></button><button className="round">♢<i>3</i></button></div></header>}

function EnterpriseApp({view,onView}:{view:string;onView:(v:string)=>void}){return <main className="app-shell"><SideBar type="enterprise" items={enterpriseNav} active={view} onView={onView}/><section className="content"><AppHeader title={view==="概览"?"下午好，陈先生":view} subtitle={view==="概览"?"2026年8月21日 · 星期五":"北京星云科技有限公司"}/>{view==="概览"&&<EnterpriseOverview onView={onView}/>} {view==="政策库"&&<PolicyLibrary/>} {view==="AI 政策助手"&&<AiAssistant/>} {view==="企业画像"&&<CompanyProfile onMatch={()=>onView("政策匹配")}/>} {view==="政策匹配"&&<PolicyMatches/>} {view==="我的关注"&&<Favorites/>}</section></main>}

function EnterpriseOverview({onView}:{onView:(v:string)=>void}){return <><section className="hero-card"><div><span className="eyebrow">企业政策体检</span><h2>您的企业画像已完成 <strong>76%</strong></h2><p>再补充 3 项研发数据，可提升政策匹配准确度，并解锁更完整的条件诊断。</p><button className="primary" onClick={()=>onView("企业画像")}>继续完善企业画像 <span>→</span></button></div><div className="profile-orbit"><div className="orbit-ring"><b>76%</b><small>画像完整度</small></div><span className="tag tag-a">高新技术</span><span className="tag tag-b">软件和信息服务</span><span className="tag tag-c">成长期</span></div></section><section className="stats"><Stat icon="◇" color="green" label="匹配政策" value="18" note="较上周新增 3 项"/><Stat icon="!" color="amber" label="即将截止" value="4" note="最近截止仅剩 12 天"/><Stat icon="✓" color="blue" label="已满足条件" value="32" note="整体条件满足率 82%"/><Stat icon="△" color="coral" label="待补充条件" value="7" note="完善后可新增 5 项匹配"/></section><div className="main-grid"><section className="panel recommendations"><div className="panel-head"><div><span className="section-kicker">为您精选</span><h3>高匹配政策</h3></div><button onClick={()=>onView("政策匹配")}>查看全部 →</button></div><div className="policy-list">{policies.slice(0,3).map(p=><PolicyRow policy={p} key={p.title}/>)}</div></section><aside className="right-stack"><section className="ai-card"><div className="ai-title"><span>✦</span><div><small>AI POLICY ASSISTANT</small><h3>政策助手</h3></div></div><p>帮您查政策、解读申报条件，回答均附政策原文依据。</p><div className="prompt-chips"><button onClick={()=>onView("AI 政策助手")}>有哪些适合我的补贴？</button><button onClick={()=>onView("AI 政策助手")}>高企认定还缺什么？</button></div><button className="ask-button" onClick={()=>onView("AI 政策助手")}><span>输入您的政策问题…</span><b>↑</b></button></section><section className="deadline-card"><div className="panel-head"><h3>申报日历</h3><button>全部</button></div><Deadline day="02" title="北京市企业技术中心认定" left="剩余 12 天"/><Deadline day="15" title="中小企业数字化转型补贴" left="剩余 25 天"/></section></aside></div></>}
function Stat({icon,color,label,value,note}:{icon:string;color:string;label:string;value:string;note:string}){return <article><span className={`stat-icon ${color}`}>{icon}</span><div><small>{label}</small><b>{value} <em>项</em></b><p>{note}</p></div></article>}
function PolicyRow({policy}:{policy:Policy}){return <article className="policy-row"><div className={`score score-${policy.score}`}><b>{policy.score}</b><small>匹配度</small></div><div className="policy-copy"><h4>{policy.title}</h4><p className="policy-meta">{policy.meta}</p><p className="policy-reason"><span>✦</span>{policy.reason}</p></div><div className="policy-aside"><b>{policy.amount}</b><small>{policy.deadline}</small><button>›</button></div></article>}
function Deadline({day,title,left}:{day:string;title:string;left:string}){return <div className="deadline"><span><b>{day}</b><small>九月</small></span><div><b>{title}</b><small>{left}</small></div></div>}

function PolicyLibrary(){const [query,setQuery]=useState("");return <section className="page-stack"><PageIntro kicker="POLICY LIBRARY" title="政策知识库" text="已收录 2,386 条经人工审核的有效政策" action="订阅政策更新"/><div className="library-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索政策名称、发布部门或政策内容"/><button>搜索政策</button></div><FilterRow labels={["全部地区","国家级","北京市","海淀区"]}/><div className="policy-catalog">{policies.filter(p=>p.title.includes(query)).map((p,i)=><article key={p.title}><div className="catalog-top"><span className={i===3?"status urgent":"status"}>{p.status}</span><span>{p.region}</span><span>{p.meta.split(" · ")[1]}</span><button>☆</button></div><h3>{p.title}</h3><p>{p.reason}。系统已完成政策关键信息提取，可查看原文依据和企业匹配情况。</p><div className="catalog-bottom"><span><small>支持力度</small><b>{p.amount}</b></span><span><small>申报截止</small><b>{p.deadline}</b></span><button>查看政策详情 →</button></div></article>)}</div></section>}
function PageIntro({kicker,title,text,action}:{kicker:string;title:string;text:string;action?:string}){return <div className="page-intro"><div><span className="section-kicker">{kicker}</span><h2>{title}</h2><p>{text}</p></div>{action&&<button className="form-submit">{action}</button>}</div>}
function FilterRow({labels}:{labels:string[]}){return <div className="filter-row">{labels.map((x,i)=><button className={i===0?"chosen":""} key={x}>{x}</button>)}<i/><select><option>全部政策类型</option></select><select><option>申报状态</option></select></div>}

function AiAssistant(){const [asked,setAsked]=useState(false);return <div className="assistant-layout"><aside className="chat-history"><button className="new-chat">＋ 发起新对话</button><small>今天</small><button className="history-active">我们公司可以申报哪些补贴？</button><button>高新企业认定条件</button><small>近7天</small><button>研发费用加计扣除政策</button><button>专精特新申报时间</button></aside><section className="conversation"><div className="conversation-head"><div className="ai-title"><span>✦</span><div><h3>AI 政策助手</h3><small>回答基于已审核政策库 · 原文可追溯</small></div></div><button>···</button></div><div className="messages"><div className="user-message">我们公司是做企业软件的，今年有哪些可以申报的补贴？</div><div className="bot-message"><div className="bot-avatar">✦</div><div><p>结合北京星云科技的企业画像，我为您筛选出 <b>6 项当前可关注政策</b>，其中两项与企业情况高度匹配：</p>{policies.slice(0,2).map(p=><div className="answer-policy" key={p.title}><span>{p.score}% 匹配</span><h4>{p.title}</h4><p>{p.reason}，{p.amount}。</p></div>)}<div className="citation"><b>原文依据 2</b><button>《技术创新资金项目申报通知》第三条 ↗</button><button>《专精特新专项申报指南》第二章 ↗</button></div><p className="ai-note">以上为政策初步匹配结果，最终申报资格以主管部门审核口径为准。</p></div></div>{asked&&<div className="bot-message"><div className="bot-avatar">✦</div><div><p>建议优先完善<b>研发费用归集</b>和<b>发明专利数量</b>。补充后，我可以重新计算匹配结果。</p></div></div>}</div><div className="composer"><div className="suggestions"><button>我还缺哪些条件？</button><button>什么时候截止？</button><button>需要准备什么材料？</button></div><div><input placeholder="继续追问政策内容…"/><button onClick={()=>setAsked(true)}>↑</button></div><small>AI回答可能存在偏差，重要申报信息请以政策原文为准</small></div></section><aside className="chat-context"><span className="section-kicker">当前企业</span><h3>北京星云科技</h3><div className="context-score"><b>76%</b><span>画像完整度</span></div><p>软件和信息技术服务业</p><p>成立 5 年 · 68 人</p><p>高新技术企业</p><button>查看完整画像 →</button><hr/><small>本次问答已使用</small><h4>企业画像 12 项</h4><h4>已审核政策 6 条</h4></aside></div>}

function CompanyProfile({onMatch}:{onMatch:()=>void}){const [step,setStep]=useState(2);return <section className="page-stack"><div className="profile-header"><div><span className="section-kicker">COMPANY PROFILE</span><h2>完善企业画像</h2><p>填写越完整，政策匹配和条件诊断越准确</p></div><div className="completion"><div><b>76%</b><small>已完成 16/21 项</small></div><span><i/></span></div></div><div className="profile-steps">{["基本信息","研发与经营","资质能力","知识产权"].map((s,i)=><button onClick={()=>setStep(i+1)} className={step===i+1?"active":step>i+1?"done":""} key={s}><span>{step>i+1?"✓":i+1}</span><b>{s}</b><small>{i===0?"已完成":i===1?"待补充3项":i===2?"已完成":"待补充2项"}</small></button>)}</div><div className="profile-form-card"><div className="form-card-title"><span>0{step}</span><div><h3>{["企业基本信息","研发与经营情况","企业资质能力","知识产权情况"][step-1]}</h3><p>这些信息将用于判断政策的基础申报条件</p></div><i>企业数据仅用于政策匹配</i></div><div className="form-grid">{step===2?<><label>上年度营业收入（万元）<input defaultValue="3280"/></label><label>上年度研发费用（万元）<input defaultValue="426"/></label><label>企业职工总数（人）<input defaultValue="68"/></label><label>研发人员数量（人）<input placeholder="请输入研发人员数量"/></label><label>近两年营收增长率（%）<input placeholder="请输入增长率"/></label><label>是否建立研发费用辅助账<select><option>请选择</option></select></label></>:<><label>企业名称<input defaultValue="北京星云科技有限公司"/></label><label>所属行业<input defaultValue="软件和信息技术服务业"/></label><label>成立日期<input defaultValue="2021-03-18"/></label><label>企业规模<select><option>中小企业</option></select></label></>}</div><div className="form-actions"><button className="secondary">保存草稿</button><button className="form-submit" onClick={()=>step<4?setStep(step+1):onMatch()}>{step<4?"保存并继续":"生成匹配结果"} →</button></div></div></section>}

function PolicyMatches(){const [selected,setSelected]=useState(0);const p=policies[selected];return <section className="page-stack"><div className="match-head"><div><span className="section-kicker">POLICY MATCHING</span><h2>政策匹配结果</h2><p>基于企业画像与已审核政策条件实时计算</p></div><div className="match-summary"><span><b>18</b>匹配政策</span><span><b>5</b>优先推荐</span><span><b>7</b>待补充条件</span></div></div><div className="match-layout"><div className="match-list"><FilterRow labels={["综合推荐","高匹配优先","即将截止"]}/>{policies.map((item,i)=><button onClick={()=>setSelected(i)} className={`match-card ${selected===i?"selected":""}`} key={item.title}><div className={`score score-${item.score}`}><b>{item.score}</b><small>匹配度</small></div><div><span className="match-tags"><i>{item.region}</i><i>{item.status}</i></span><h3>{item.title}</h3><p>{item.reason}</p><small>{item.meta}</small></div><span className="match-arrow">›</span></button>)}</div><aside className="diagnosis"><div className="diagnosis-head"><span className="section-kicker">MATCH REPORT</span><h3>{p.title}</h3><div><b>{p.score}</b><span>综合匹配度<small>建议优先关注</small></span></div></div><div className="condition-overview"><span><b>5</b><small>已满足</small></span><span><b>1</b><small>部分满足</small></span><span><b>1</b><small>待补充</small></span></div><div className="condition-list"><Condition state="pass" title="所属行业" text="软件和信息技术服务业，符合重点支持领域"/><Condition state="pass" title="企业规模" text="职工68人、营收3280万元，符合中小企业标准"/><Condition state="partial" title="知识产权" text="已有3项软著，建议补充发明专利以提高竞争力"/><Condition state="unknown" title="研发人员占比" text="尚未填写研发人员数量，暂时无法判断"/></div><button className="form-submit">补充缺失信息 →</button><button className="consult-button">预约顾问人工复核</button><p className="diagnosis-note">匹配结果仅供申报规划参考，最终以主管部门审核为准。</p></aside></div></section>}
function Condition({state,title,text}:{state:string;title:string;text:string}){return <div className={`condition ${state}`}><span>{state==="pass"?"✓":state==="partial"?"!":"?"}</span><div><b>{title}</b><p>{text}</p></div></div>}
function Favorites(){return <section className="page-stack"><PageIntro kicker="MY COLLECTION" title="我的关注" text="收藏的政策与申报提醒"/><div className="policy-catalog">{policies.slice(0,2).map(p=><article key={p.title}><div className="catalog-top"><span className="status">已关注</span><span>{p.region}</span></div><h3>{p.title}</h3><p>{p.reason}</p><div className="catalog-bottom"><span><small>申报截止</small><b>{p.deadline}</b></span><button>查看政策详情 →</button></div></article>)}</div></section>}

function AdminApp({view,onView}:{view:string;onView:(v:string)=>void}){return <main className="app-shell admin-app"><SideBar type="admin" items={adminNav} active={view} onView={onView}/><section className="content"><AppHeader title={view} subtitle="政策运营管理中心 · 今日数据已更新"/>{view==="运营概览"&&<AdminOverview onView={onView}/>} {view==="数据源管理"&&<SourceManagement/>} {view==="采集任务"&&<CollectionTasks/>} {view==="政策审核"&&<ReviewQueue/>} {view==="政策管理"&&<PolicyManagement/>} {view==="企业与线索"&&<EnterpriseLeads/>} {view==="AI 问答记录"&&<QaLogs/>}</section></main>}
const reviewRows=[{title:"北京市促进专精特新企业高质量发展若干措施",source:"北京市经济和信息化局",risk:"关键字段低置信度",confidence:"72%",time:"16:21"},{title:"海淀区2026年度科技创新专项申报通知",source:"海淀区人民政府",risk:"疑似年度更新",confidence:"88%",time:"15:54"},{title:"关于开展企业技术中心认定工作的通知",source:"北京市发展改革委",risk:"截止时间待确认",confidence:"64%",time:"15:32"},{title:"中小企业数字化转型城市试点支持方案",source:"工业和信息化部",risk:"疑似重复政策",confidence:"91%",time:"14:18"}];
function AdminOverview({onView}:{onView:(v:string)=>void}){return <section className="page-stack"><div className="admin-banner"><div><span className="eyebrow">今日运营摘要</span><h2>有 12 条政策等待人工审核</h2><p>其中 4 条因来源异常或关键字段置信度较低，需要优先处理。</p><button onClick={()=>onView("政策审核")}>进入审核队列 →</button></div><div className="admin-donut"><b>86%</b><small>自动处理率</small></div></div><section className="stats admin-stats"><Stat icon="↓" color="green" label="今日采集" value="48" note="新增政策 21 条"/><Stat icon="✓" color="blue" label="今日发布" value="19" note="平均审核 6.8 分钟"/><Stat icon="!" color="amber" label="异常数据" value="4" note="2 条来源无法访问"/><Stat icon="◎" color="coral" label="新增企业" value="27" note="高意向企业 6 家"/></section><div className="admin-grid"><section className="panel"><div className="panel-head"><div><span className="section-kicker">REVIEW QUEUE</span><h3>待处理政策</h3></div><button onClick={()=>onView("政策审核")}>查看全部 →</button></div><ReviewTable compact/></section><section className="panel activity-panel"><div className="panel-head"><h3>实时动态</h3><button>今天</button></div><Activity time="16:28" title="采集任务完成" text="北京市经信局新增 8 条政策"/><Activity time="16:12" title="企业完成测评" text="北京云帆智造，匹配 12 项政策"/><Activity time="15:46" title="政策审核发布" text="周运营发布科技资金政策"/><Activity time="15:20" title="问答转人工" text="企业咨询高企认定复审问题"/></section></div></section>}
function Activity({time,title,text}:{time:string;title:string;text:string}){return <div className="activity"><span>{time}</span><i/><div><b>{title}</b><p>{text}</p></div></div>}
function ReviewTable({compact=false,onOpen}:{compact?:boolean;onOpen?:()=>void}){return <div className="data-table"><div className="table-row table-head"><span>政策名称</span><span>异常类型</span><span>置信度</span><span>采集时间</span><span>操作</span></div>{reviewRows.slice(0,compact?3:4).map(r=><div className="table-row" key={r.title}><span><b>{r.title}</b><small>{r.source}</small></span><span><i className="risk-dot"/>{r.risk}</span><span><b className={Number(r.confidence.slice(0,-1))<75?"low-confidence":""}>{r.confidence}</b></span><span>{r.time}</span><span><button onClick={onOpen}>开始审核</button></span></div>)}</div>}
function ReviewQueue(){const [open,setOpen]=useState(false);return <section className="page-stack"><PageIntro kicker="POLICY REVIEW" title="政策审核队列" text="AI预处理完成后，由运营人员核对原文并确认发布"/>{open?<ReviewDetail onBack={()=>setOpen(false)}/>:<><FilterRow labels={["全部风险","低置信度 5","来源异常 2","疑似重复 3"]}/><ReviewTable onOpen={()=>setOpen(true)}/><p className="table-tip">点击“开始审核”进入原文对照审核页</p></>}</section>}
function ReviewDetail({onBack}:{onBack:()=>void}){return <div className="review-detail"><div className="review-toolbar"><button onClick={onBack}>← 返回审核队列</button><span>政策编号：COL-20260821-0382</span><div><button className="secondary">退回重解析</button><button className="publish">审核通过并发布</button></div></div><div className="review-columns"><section className="source-document"><div className="document-head"><span>政策原文</span><button>打开来源网页 ↗</button></div><article><p className="doc-source">北京市经济和信息化局</p><h2>北京市促进专精特新企业高质量发展若干措施</h2><p className="doc-number">京经信发〔2026〕18号</p><h3>一、支持对象</h3><p>在北京市依法注册，具有独立法人资格，符合国家和本市产业发展方向的专精特新中小企业。</p><h3>二、支持内容</h3><p className="highlight">对符合条件的国家级专精特新“小巨人”企业，给予最高不超过100万元的一次性奖励。</p><h3>三、申报条件</h3><p>企业近两年主营业务收入平均增长率不低于5%，研发费用占营业收入比重不低于3%。</p><p>申报企业应拥有与主营业务相关的自主知识产权。</p></article></section><section className="extracted-fields"><div className="document-head"><span>AI结构化结果</span><span className="confidence-pill">综合置信度 72%</span></div><div className="field-review"><label>政策名称 <em>98%</em><input defaultValue="北京市促进专精特新企业高质量发展若干措施"/></label><div className="two-fields"><label>发布部门 <em>96%</em><input defaultValue="北京市经济和信息化局"/></label><label>政策层级 <em>93%</em><select><option>市级</option></select></label></div><div className="two-fields"><label>支持额度 <em className="low">68%</em><input defaultValue="最高100万元"/></label><label>截止日期 <em className="low">42%</em><input placeholder="原文未明确，请人工确认"/></label></div><label>适用对象 <em>89%</em><textarea defaultValue="北京市依法注册的专精特新中小企业；国家级专精特新“小巨人”企业"/></label><label>结构化申报条件 <em>76%</em></label><div className="rule-row"><select><option>营收增长率</option></select><select><option>不低于</option></select><input defaultValue="5"/><span>%</span></div><div className="rule-row"><select><option>研发费用占比</option></select><select><option>不低于</option></select><input defaultValue="3"/><span>%</span></div><label>AI摘要 <em>84%</em><textarea defaultValue="面向北京市专精特新企业提供资金奖励与培育支持，国家级专精特新“小巨人”企业最高可获100万元。"/></label></div></section></div></div>}

function SourceManagement(){const sources=[["工业和信息化部","国家级","正常","12分钟前","每日2次"],["北京市经济和信息化局","北京市","正常","18分钟前","每4小时"],["北京市科学技术委员会","北京市","正常","26分钟前","每4小时"],["海淀区人民政府","海淀区","结构异常","2小时前","每日1次"],["国家税务总局","国家级","正常","3小时前","每日1次"],["北京市发展改革委","北京市","需要验证","1天前","每日1次"]];return <section className="page-stack"><PageIntro kicker="DATA SOURCES" title="重点网站数据源" text="配置政府网站采集频率，监控页面结构与数据质量" action="＋ 添加数据源"/><div className="source-grid">{sources.map(s=><article key={s[0]}><div><span className={s[2]==="正常"?"source-ok":"source-warn"}>{s[2]}</span><button>···</button></div><h3>{s[0]}</h3><p>覆盖范围：{s[1]}</p><dl><div><dt>最近同步</dt><dd>{s[3]}</dd></div><div><dt>采集频率</dt><dd>{s[4]}</dd></div></dl><button className="source-action">查看采集记录 →</button></article>)}</div></section>}
function CollectionTasks(){return <section className="page-stack"><PageIntro kicker="COLLECTION TASKS" title="政策采集任务" text="自动采集、解析和异常处理记录" action="立即执行采集"/><section className="stats admin-stats"><Stat icon="↻" color="green" label="运行中" value="3" note="预计8分钟完成"/><Stat icon="✓" color="blue" label="今日成功" value="46" note="新增21条政策"/><Stat icon="!" color="amber" label="部分成功" value="2" note="附件解析失败"/><Stat icon="×" color="coral" label="今日失败" value="1" note="页面结构已变化"/></section><div className="panel"><ReviewTable/></div></section>}
function PolicyManagement(){return <section className="page-stack"><PageIntro kicker="POLICY MANAGEMENT" title="已发布政策" text="管理政策版本、有效状态及前台展示" action="＋ 手工录入政策"/><FilterRow labels={["全部 2,386","有效 2,142","即将失效 38","已下架 206"]}/><div className="panel"><ReviewTable/></div></section>}
function EnterpriseLeads(){const rows=[["北京星云科技有限公司","76% / 18项","咨询专精特新","周运营","待首次联系"],["北京云帆智造有限公司","100% / 12项","预约人工复核","李顾问","跟进中"],["海淀数科创新中心","64% / 8项","浏览高企政策5次","未分配","待分配"],["中科智联软件有限公司","92% / 21项","提交申报咨询","王顾问","已联系"]];return <section className="page-stack"><PageIntro kicker="ENTERPRISE LEADS" title="企业与服务线索" text="基于测评、匹配和问答行为识别企业需求" action="导出企业列表"/><section className="stats admin-stats"><Stat icon="◎" color="green" label="注册企业" value="836" note="本月新增127家"/><Stat icon="✓" color="blue" label="完成测评" value="524" note="完成率62.7%"/><Stat icon="✦" color="amber" label="高意向线索" value="68" note="待跟进12家"/><Stat icon="△" color="coral" label="今日待联系" value="9" note="3家已超24小时"/></section><div className="data-table lead-table"><div className="table-row table-head"><span>企业名称</span><span>画像/匹配</span><span>意向信号</span><span>负责人</span><span>跟进状态</span></div>{rows.map(r=><div className="table-row" key={r[0]}>{r.map((c,i)=><span key={c}>{i===0?<><b>{c}</b><small>软件和信息技术服务业</small></>:c}</span>)}</div>)}</div></section>}
function QaLogs(){const rows=[["北京星云科技","我们公司可以申报哪些补贴？","已引用2条政策","正向反馈"],["云帆智造","去年申报过的项目今年还能再报吗？","需人工确认","已转人工"],["中科智联","高企认定对研发人员有什么要求？","已引用1条政策","正向反馈"]];return <section className="page-stack"><PageIntro kicker="AI QA AUDIT" title="AI问答记录" text="检查回答依据、用户反馈和低置信度问题"/><FilterRow labels={["全部问答","已转人工 8","低置信度 5","用户点踩 3"]}/><div className="qa-list">{rows.map(q=><article key={q[1]}><div className="avatar">{q[0][0]}</div><div><small>{q[0]} · 今天 15:42</small><h3>{q[1]}</h3><p>{q[2]}</p></div><span>{q[3]}</span><button>查看对话 →</button></article>)}</div></section>}
